name: AntiExplosion 编译

on:
  #对应的是 UTC 时间，需要转换，0 代表北京时间8点，每个月4日/18日12点编译一次
  #关闭则手动编译
  workflow_dispatch:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Test
        run: mvn test
      - name: Package
        run: mvn package
        
      - name: 检测编译完的插件
        run: |
          mkdir -p ./upload
          cp -f target/*.jar ./upload/
          cd ./upload/
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        
      - name: 上传插件jar
        uses: actions/upload-artifact@v4
        with:
          name: AntiExplosion
          path: target/*.jar
 
      - name: 生成标签，上传固件 
        uses: ncipollo/release-action@main
        with:
          tag: AntiExplosion
          artifacts: ${{ env.FIRMWARE }}/*
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ====================🧊插件信息🧊=======================
            ➦ 📒 插件名称：AntiExplosion
            ➦ 💻 插件平台：Minecraft
            ➦ ⚽ 插件源码：https://github.com/MCZLF/plugin-AntiExplosion
